### ISSUE TITLE
Замечания лаб 1 @FILIN955

### ISSUE THREAD

**Issue by ananasn** [ITMOPython-2023/lab1#3]
Замечания указанные ниже нужно исправить
@FILIN955

1. Код оформлен не по PEP8. Обратите внимание как операторы должны обрамляться пробелами. 
https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements

2.  Записи типа `row[6], row[4], row[1]` и тд плохо читаемы, лучше давать таким объектам названия и использовать по названию. Пример:
```python
MAX_NAME_LIM = 30

... 
book_name = book[1]
if len(book_name) > MAX_NAME_LIM:
....
````
3. Это условие не сработает `if s in (row[3] or row[4]) and (('2015' or '2018') in row[6]):`. Программа не выдает ожидаемы результат.
![Снимок экрана от 2023-10-16 21-45-41](https://github.com/ITMOPython-2023/lab1/assets/8919470/d4090d4c-3755-4fb7-bebb-165fb6676b36)

В ответах ниже объясните почему условие не работает. Ниже подсказка.

```python
# Это выражение вернет то, что слева от оператора or
>>> 'Автор2' or 'Автор1'
'Автор2'

>>> '2015' or '2018'
'2015'

>>> ('2015' or '2018') in '2018'
False
```

5. Переменная `book` названа некорректно, совершенно непонятно какие книги она хранит. Я бы назвала `filtered_book`.
7. Максимальная длина строки по PEP8 -- 79 символов. У вас не соблюдается.
8.  Такие записи `books[r][3]` лучше разбивать на несколько инструкций для улучшения читаемости кода. Например:
```python
random_book = books[r]
author = random_book[3]
title = random_book[1]
date = random_book[6]
file.write(f'{r}, Автор - {author}, Книга - {title}, дата: {date}\n')
```

**Comment by FILIN955** [comment]
Ошибка в том, что если было совпадение в 2015, то 2018 уже не искалось
