### ISSUE TITLE
Замечания лаб1 @KOA1KO

### ISSUE THREAD

**Issue by ananasn** [ITMOPython-2023/lab1#4]
@KOA1KO

Замечания ниже нужно исправить.

1. В программе названия переменных должны иметь смысл, название отражает суть того, что содержит переменная. Отсюда применение переменных с названиями `c, f, cnt` ... недопустимо. Например, вместо cnt используем long_names_num, а `с` -> `records_num`
2. Используйте `f-строки`, это более предпочтительнее чем конкатенация (сложение), `print('dfsdfs', 'fdsfsd')` или несколько идущие подряд `print`
    ```python
    print(f'Кол-во записей: {entries_num}')
    ```
3. Не используйте магические числа (типа 2, 30, 21 и тд) в программе, суть которых понятна только вам. Обозначайте их как константы. Константы обычно указываются вначале программы после блока импортов. Пример:
  ```python
    import csv
    
    MAX_NAME = 30
    ...
  ```
4. По PEP8 длина строки должна быть не более 79 ( а для комментариев до 72).

5. Такие записи i[6][8], i[6][9]  лучше разбивать на несколько инструкций для улучшения читаемости кода. А записи line[1] именовать нормально. Например:
  ```python
  random_book = books[r]
  author = random_book[3]
  title = random_book[1]
  date = random_book[6]
  file.write(f'{r}, Автор - {author}, Книга - {title}, дата: {date}\n')
  ```
7. Вот такие вещи `int(i[6][8] + i[6][9])` делаются срезом 
```python
# Неверно
if int(i[6][8] + i[6][9]) < 16:
    ...

#Верно

date = book[6]
year = int(date[8:10])

if year < 16:
    ...
```
8.  Вместо счетчика ` c1 += 1` лучше воспользоваться интератором и функцией next.
```python
# Так не надо
for i in fr:
        c1 += 1

        if c1 == 1:
            continue

# Лучше так
next(books)
for book in books:
        ...
```

**Comment by KOA1KO** [comment]
The work on the errors is completed
